### ISSUE TITLE
arrow formatting

### ISSUE THREAD

**Issue by ursi** [hbr/Lambda-Calculus#4]
Would you be interested in updating `\to_r^*` to `\to_{r^*}` and other analogous changes? I might be willing to do it, but before I consider it I'd like to know if you'd be open to it.

**Comment by hbr** [comment]
The change seems to be reasonable, because the star or similar superscripts belong to the relation and not the arrow.

**Comment by ursi** [comment]
cool, I think it will help with the initial readability of the non-horizontal arrows
