### ISSUE TITLE
Tildes

### ISSUE THREAD

**Issue by ursi** [hbr/Lambda-Calculus#6]
I see you use mixture `r^\sim` and `reqv{r}` for `r~`. Do you think it would be appropriate to use `\tilde{r}` instead? this would put the tilde on top of the `r` instead of in the exponent position.

**Comment by hbr** [comment]
The expression `r^\sim` is the equivalence closure of `r`, like `r^+` is the transitive closure and `r^*` is the reflexive transitive closure. I.e. I consistently put closure operators as superscripts. It might be confusing, if some closure operators are denoted by superscripts, and another by a tilde on top.

**Comment by ursi** [comment]
aright, makes sense. Is there are a particular reason you use two different ways of achieving the it? (`\sim` and `\reqv`)?

**Comment by hbr** [comment]
No, there is no reason. Maybe I started with `\sim` and later introduced a macro to write it more symbolically. But obviously it did not pay off.

Maybe the latex source is more readable with `r^\sim` and `r^*` than with some cryptic macros. But it is a matter of taste.
