### ISSUE TITLE
Error in the Pair-Example (pdf-version)

### ISSUE THREAD

**Issue by klartext** [hbr/Lambda-Calculus#7]
In the pdf, page 9, pair with type annotations has
```
first = K p
```
and
```
second = KI p
```
The html version is correct.

**Comment by hbr** [comment]
Thanks for the comment. However I see the html and the pdf version identical.

Where do you see the difference? Both documents come from the same source.

**Comment by klartext** [comment]
OK, I was wring with "The html version is correct.".
I looked at the wrong place in the html.

In the pdf, page 8:
```
first p := p K
second p := p KI
```

page 9 (type annotations removed):
```
first p := K p
second p := KI p
```

**Comment by hbr** [comment]
Thanks for the hint. It should be correct now in both versions.
