### ISSUE TITLE
Lemma 3.12 variable typo?

### ISSUE THREAD

**Issue by AlienKevin** [hbr/Lambda-Calculus#9]
On page 25:
<img width="1003" alt="Screenshot 2023-02-23 at 12 15 33 PM" src="https://user-images.githubusercontent.com/22850071/220981125-bd6bd072-846d-4b31-9e69-00e9a781c806.png">

It seems that C should be replaced with D?

Thanks for writing this paper btw, it's really helpful for learning about dependent types. I like how you start from the basics and prove things step by step. Some other papers tend to skip around because they assume more background in the subject.

**Comment by hbr** [comment]
Typo corrected. Thanks for reporting it.
